---
title: "R/Medicine Schedule"
format: 
  html:
    code-fold: false
    echo: false
    warning: false
    message: false
---

-   All times EDT

-   The conference runs in two parallel tracks for the first two days
    of workshops, demos, and panels

-   The talks on the final two days run in a single track

```{r}
library(lubridate)
library(gt)

# Create HTML pattern for talk links:
link_style <- "color:black; font-weight:500; text-decoration:underline;"
hover_effect <- "onmouseover='this.style.fontStyle=\"none\"' onmouseout='this.style.fontStyle=\"normal\"'" # change fontStyle to "italic" for italic on hover
html_pattern <- glue::glue(
    "<div>{{1}}<br><a href='{{5}}' style='{link_style}' {hover_effect}>{{2}}</a><br>{{3}} {{4}}</div>"
)
```

<!-- <!-- # Workshop/Demo Day 1 {.hidden} --> 

<!-- ```{r, day1} -->
<!-- # Day 1 -->
<!-- schedule_day_1 <- -->
<!--   dplyr::tribble( -->
<!--     ~start_time,  -->
<!--     ~end_time,  -->
<!--     ~track, -->
<!--     ~t_type,  -->
<!--     ~t_title,  -->
<!--     ~t_speakers,   -->
<!--     ~t_companies, -->
<!--     ~url_link, -->

<!--     "2025-06-09 10:00",  -->
<!--     "2025-06-09 11:00",  -->
<!--     "A", -->
<!--     "Demo",  -->
<!--     "In the Nix of Time: Creating a reproducible analytical environment with Nix and {rix}",  -->
<!--     "Eric Nantz",  -->
<!--     "Eli Lilly", -->
<!--     "abstracts.html#in-the-nix-of-time", -->

<!--     "2025-06-09 10:00",  -->
<!--     "2025-06-09 11:00",  -->
<!--     "B", -->
<!--     "Demo",  -->
<!--     "A framework for cohort building in R: the CohortConstructor package for data mapped to the OMOP Common Data Model ",  -->
<!--     "Nuria Mercade-Besora & Edward Burn",  -->
<!--     "University of Oxford", -->
<!--     "workshops.html#a-framework-for-cohort-building-in-r-the-cohortconstructor-package-for-data-mapped-to-the-omop-common-data-model", -->

<!--     "2025-06-09 11:00",  -->
<!--     "2025-06-09 14:00",  -->
<!--     "A", -->
<!--     "Workshop",  -->
<!--     "Promover la Equidad Científica: Una Introducción al uso de R para la programación en Bioestadística y Ciencia de Datos, en Español",  -->
<!--     "Catalina Canizares-Escobar & Francisco Cardozo",  -->
<!--     "Florida International University", -->
<!--     "workshops.html#promover-la-equidad-científica-una-introducción-al-uso-de-r-para-la-programación-en-bioestadística-y-ciencia-de-datos-en-español.", -->

<!--     "2025-06-09 11:00",  -->
<!--     "2025-06-09 14:00",  -->
<!--     "B", -->
<!--     "Workshop",  -->
<!--     "Introduction to R for Clinical Data",  -->
<!--     "Rich Hanna",  -->
<!--     "Children's Hospital of Philadelphia", -->
<!--     "workshops.html#introduction-to-r-for-clinical-data", -->

<!--     "2025-06-09 14:00",  -->
<!--     "2025-06-09 14:30", -->
<!--     "", -->
<!--     "Break",  -->
<!--     "", -->
<!--     "", -->
<!--     "", -->
<!--     "", -->

<!--     "2025-06-09 14:30",  -->
<!--     "2025-06-09 17:30",  -->
<!--     "A", -->
<!--     "Workshop",  -->
<!--     "R package development with GitHub Pages and pkgdown",  -->
<!--     "Melissa Van Bussel",  -->
<!--     "Statistics Canada", -->
<!--     "workshops.html#r-package-development-with-github-pages-and-pkgdown", -->

<!--     "2025-06-09 14:30",  -->
<!--     "2025-06-09 17:30",  -->
<!--     "B", -->
<!--     "Workshop",  -->
<!--     "The power of {targets} package for reproducible data science",  -->
<!--     "Rahul Sangole",  -->
<!--     "Apple", -->
<!--     "workshops.html#the-power-of-targets-package-for-reproducible-data-science", -->

<!--     "2025-06-09 17:30",  -->
<!--     "2025-06-09 18:30",  -->
<!--     "A", -->
<!--     "Demo",  -->
<!--     "REDCapSync and RosyREDCap: two development R packages using the REDCap API for standardized data pipelines and exploratory data analysis",  -->
<!--     "Brandon Rose",  -->
<!--     "University of Miami/Jackson Memorial Hospital", -->
<!--     "abstracts.html#redcapsync-and-rosyredcap", -->

<!--     "2025-06-09 17:30",  -->
<!--     "2025-06-09 18:30",  -->
<!--     "B", -->
<!--     "Demo",  -->
<!--     "Biomarker Identification by Means of Frequent Itemset Mining and Contrast Set Mining",  -->
<!--     "Paul Kowalczyk",  -->
<!--     "HAcKerS LaB", -->
<!--     "abstracts.html#biomarker-identification" -->
<!--   ) |> -->
<!--   dplyr::mutate( -->
<!--     t_speakers = dplyr::if_else(t_companies != "", paste0(t_speakers, ","), t_speakers), -->
<!--     duration = time_length(ymd_hm(end_time) - ymd_hm(start_time), unit = "mins") -->
<!--   ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- # Create a table for the day of events -->
<!-- gt(schedule_day_1) |> -->
<!--   tab_header( -->
<!--     title = md("<br>Workshop/Demo Day 1<br>Monday, June 9, 2025<br><br>")) |> # <- insert the date -->
<!--   fmt_time(columns = c(start_time, end_time), time_style = "h_m_p") |> -->
<!--   fmt_duration( -->
<!--     columns = duration, -->
<!--     input_units = "minutes", -->
<!--     output_units = c("hours", "minutes") -->
<!--   ) |> -->
<!--   cols_move(columns = duration, after = end_time) |> -->
<!--   cols_merge( -->
<!--     columns = c(t_type, t_title, t_speakers, t_companies, url_link), -->
<!--     pattern = html(html_pattern) -->
<!--   ) |> -->
<!--   cols_label( -->
<!--     start_time ~ "Start Time", -->
<!--     end_time ~ "End Time", -->
<!--     duration ~ "Duration", -->
<!--     track ~ "Track", -->
<!--     t_type ~ "" -->
<!--   ) |> -->
<!--   cols_align(align = "center") |> -->
<!--   cols_width( -->
<!--     c(start_time, end_time, duration, track) ~ px(90), -->
<!--     everything() ~ px(600) -->
<!--   ) |> -->
<!--   opt_align_table_header(align = "left") |> -->
<!--   tab_options( -->
<!--     heading.background.color = "lightblue", -->
<!--     column_labels.background.color = "gray85", -->
<!--     table.width = pct(100) -->
<!--   ) |> -->
<!--   tab_style( -->
<!--     locations = cells_body(rows = t_type == "Break"), -->
<!--     style = cell_fill(color = "bisque") -->
<!--   ) -->
<!-- ``` -->

# Workshop/Demo Day 1

```{r, day2}
# Day 2
schedule_day_2 <-
    dplyr::tribble(
        ~start_time                                                       ,
        ~end_time                                                         ,
        ~track                                                            ,
        ~t_type                                                           ,
        ~t_title                                                          ,
        ~t_speakers                                                       ,
        ~t_companies                                                      ,
        ~url_link     ,
        
        "2026-05-05 10:00"                                                ,
        "2026-05-05 11:00"                                                ,
        "A"                                                               ,
        "Demo"                                                        ,
        "You Should Probably Map That: Introduction to Geospatial Analysis in R"                             ,
        "Anjile An"                                                      ,
        "Weill Cornell Medical College"                             ,
        "workshops.html#mapping",
        
        "2026-05-05 10:00"                                                ,
        "2026-05-05 11:00"                                                ,
        "B"                                                               ,
        "Demo"                                                        ,
        "Interactive and Instant: GenAI-driven Creation of Clinical Trial Applications"                             ,
        "Marcin Dubel"                                                      ,
        "Appsilon"                             ,
        "workshops.html#tealflow",
        
        "2026-05-05 11:00"                                                ,
        "2026-05-05 14:00"                                                ,
        "A"                                                               ,
        "Workshop"                                                        ,
        "Introduction to R for Clinical Data"                             ,
        "Rich Hanna"                                                      ,
        "Children's Hospital of Philadelphia"                             ,
        "workshops.html#r101"                                             ,
        
        "2026-05-05 11:00"                                                ,
        "2026-05-05 14:00"                                                ,
        "B"                                                               ,
        "Workshop"                                                        ,
        "Promover la Equidad Científica: Introducción a R"                ,
        "Catalina Cañizares-Escobar, New York University;"                ,
        "Francisco Cardozo, University of Miami"                          ,
        "workshops.html#equidad"                                          ,
        
        "2026-05-05 14:00"                                                ,
        "2026-05-05 14:30"                                                ,
        ""                                                                ,
        "Break"                                                           ,
        ""                                                                ,
        ""                                                                ,
        ""                                                                ,
        ""                                                                ,
        
        "2026-05-05 14:30"                                                ,
        "2026-05-05 17:30"                                                ,
        "A"                                                               ,
        "Workshop"                                                        ,
        "Mastering Clinical Data Summaries with {gtsummary} and AI"       ,
        "Daniel D. Sjoberg, Genentech;"                                   ,
        "Shannon Pileggi, The Prostate Cancer Clinical Trials Consortium" ,
        "workshops.html#gtsummary",
        
        "2026-05-05 14:30"                                                ,
        "2026-05-05 15:30"                                                ,
        "B"                                                               ,
        "Demo"                                                            ,
        "Building Accessible, On-Brand Documents with Quarto"             ,
        "Charlotte Wickham"                                               ,
        "Posit"                                                           ,
        "workshops.html#quarto-docs",
        
        "2026-05-05 15:30"                                                ,
        "2026-05-05 16:30"                                                ,
        "B"                                                               ,
        "Panel"                                                           ,
        "R and RedCap Panel Discussion"                                   ,
        "Raymond Balise, Brandon Rose, Rich Hanna, and others"            ,
        ""                                                                ,
        "workshops.html#redcap",
        
        "2026-05-05 16:30"                                                ,
        "2026-05-05 17:30"                                                ,
        "B"                                                               ,
        "Demo"                                                            ,
        "Ctrialsgov R Package"                                            ,
        "Michael Kane"                                                    ,
        "MD Anderson Cancer Center"                                       ,
        "workshops.html#ctrialsgov"
    ) |>
    dplyr::mutate(
        t_speakers = dplyr::if_else(
            t_companies != "",
            paste0(t_speakers, ","),
            t_speakers
        ),
        duration = time_length(
            ymd_hm(end_time) - ymd_hm(start_time),
            unit = "mins"
        )
    )
```

```{r}
# Create a table for the day of events
gt(schedule_day_2) |>
    tab_header(title = md("<br>Tuesday, May 5, 2026<br><br>")) |> # <- insert the date
    fmt_time(columns = c(start_time, end_time), time_style = "h_m_p") |>
    fmt_duration(
        columns = duration,
        input_units = "minutes",
        output_units = c("hours", "minutes")
    ) |>
    cols_move(columns = duration, after = end_time) |>
    cols_merge(
        columns = c(t_type, t_title, t_speakers, t_companies, url_link),
        pattern = html(html_pattern)
    ) |>
    cols_label(
        start_time ~ "Start Time",
        end_time ~ "End Time",
        duration ~ "Duration",
        track ~ "Track",
        t_type ~ ""
    ) |>
    cols_align(align = "center") |>
    cols_width(
        c(start_time, end_time, duration, track) ~ px(90),
        everything() ~ px(600)
    ) |>
    opt_align_table_header(align = "left") |>
    tab_options(
        heading.background.color = "lightblue",
        column_labels.background.color = "gray85",
        table.width = pct(100)
    ) |>
    tab_style(
        locations = cells_body(rows = t_type == "Break"),
        style = cell_fill(color = "darkseagreen2", alpha = 0.5)
    ) |>
    tab_style(
        locations = cells_body(rows = t_type == "Questions"),
        style = cell_fill(color = "darkseagreen3", alpha = 0.5)
    ) |>
    tab_style(
        locations = cells_body(rows = t_type == "Session Intro"),
        style = cell_fill(color = "darkseagreen3", alpha = 0.5)
    )
```

# Workshop/Demo Day 2 

```{r, day3}
# Day 3
schedule_day_3 <-
    dplyr::tribble(
        ~start_time                                                          ,
        ~end_time                                                            ,
        ~track                                                               ,
        ~t_type                                                              ,
        ~t_title                                                             ,
        ~t_speakers                                                          ,
        ~t_companies                                                         ,
        ~url_link                                                            ,
        
        "2026-05-06 10:00"                                                   ,
        "2026-05-06 11:00"                                                   ,
        "A"                                                                  ,
        "Demo"                                                           ,
        "Demonstration on making Shiny dashboards accessible for users who rely on screen readers and keyboards"                          ,
        "Abigail Stamm & Eric Kvale"                                                ,
        "Minnesota Department of Health"                                                              ,
        "workshops.html#accessible",
        
        "2026-05-06 10:00"                                                   ,
        "2026-05-06 11:00"                                                   ,
        "B"                                                                  ,
        "Demo"                                                           ,
        "REDCapSync and RosyREDCap: Advanced REDCap API for Even the Basic R User; Standardized Data Pipelines and a Companion Shiny App for any REDCap Project"                          ,
        "Brandon Rose & Natalie Goulett"                                                ,
        "University of Texas Southwestern Medical Center"                                                              ,
        "workshops.html#redcapdemo",
        
        "2026-05-06 11:00"                                                   ,
        "2026-05-06 14:00"                                                   ,
        "A"                                                                  ,
        "Workshop"                                                           ,
        "Working with Larger than Memory Data in R"                          ,
        "François Michonneau"                                                ,
        "Posit"                                                              ,
        "workshops.html#big-data"                                            ,
        
        "2026-05-06 11:00"                                                   ,
        "2026-05-06 14:00"                                                   ,
        "B"                                                                  ,
        "Workshop"                                                           ,
        "ggplot2 for Data Visualisation: Creativity, Clarity, Accessibility" ,
        "Cara Thompson"                                                      ,
        ""                                                                   ,
        "workshops.html#ggplot2"  ,
        
        "2026-05-05 14:00"                                                   ,
        "2026-05-05 14:30"                                                   ,
        ""                                                                   ,
        "Break"                                                              ,
        ""                                                                   ,
        ""                                                                   ,
        ""                                                                   ,
        ""                                                                   ,
        "2026-05-05 14:30"                                                   ,
        "2026-05-05 17:30"                                                   ,
        "A"                                                                  ,
        "Workshop"                                                           ,
        "LLMs for Data Analysis in R"                                        ,
        "Sara Altman"                                                        ,
        "Posit"                                                              ,
        "workshops.html#llms"                                                ,
        
        "2026-05-05 14:30"                                                   ,
        "2026-05-05 17:30"                                                   ,
        "B"                                                                  ,
        "Workshop"                                                           ,
        "No more copy and paste! Parameterized plots and reports with R and Quarto"                                                                ,
        "Nicola Rennin"                                                                   ,
        ""                                                                   ,
        "workshops.html#parameterized-reports"
    ) |>
    dplyr::mutate(
        t_speakers = dplyr::if_else(
            t_companies != "",
            paste0(t_speakers, ","),
            t_speakers
        ),
        duration = time_length(
            ymd_hm(end_time) - ymd_hm(start_time),
            unit = "mins"
        )
    )
```

```{r}
# Create a table for the day of events
gt(schedule_day_3) |>
    tab_header(title = md("<br>Wednesday, May 6, 2026<br><br>")) |> # <- insert the date
    fmt_time(columns = c(start_time, end_time), time_style = "h_m_p") |>
    fmt_duration(
        columns = duration,
        input_units = "minutes",
        output_units = c("hours", "minutes")
    ) |>
    cols_move(columns = duration, after = end_time) |>
    cols_merge(
        columns = c(t_type, t_title, t_speakers, t_companies, url_link),
        pattern = html(html_pattern)
    ) |>
    cols_label(
        start_time ~ "Start Time",
        end_time ~ "End Time",
        duration ~ "Duration",
        track ~ "Track",
        t_type ~ ""
    ) |>
    cols_align(align = "center") |>
    cols_width(
        c(start_time, end_time, duration, track) ~ px(90),
        everything() ~ px(600)
    ) |>
    opt_align_table_header(align = "left") |>
    tab_options(
        heading.background.color = "lightblue",
        column_labels.background.color = "gray85",
        table.width = pct(100)
    ) |>
    tab_style(
        locations = cells_body(rows = t_type == "Break"),
        style = cell_fill(color = "darkseagreen2", alpha = 0.5)
    ) |>
    tab_style(
        locations = cells_body(rows = t_type == "Questions"),
        style = cell_fill(color = "darkseagreen3", alpha = 0.5)
    ) |>
    tab_style(
        locations = cells_body(rows = t_type == "Session Intro"),
        style = cell_fill(color = "darkseagreen3", alpha = 0.5)
    )
```

# Meeting Day 1 

```{r, day4}
# Day 4
schedule_day_4 <-
  dplyr::tribble(
    ~start_time,
    ~end_time,
    ~t_type,
    ~t_title,
    ~t_speakers,
    ~t_companies,
    ~url_link,

    "2026-05-07 11:00",
    "2026-05-07 11:15",
    "Opening Remarks",
    "",
    "Emily Zabor",
    "Cleveland Clinic",
    "",

    "2026-05-07 11:15",
    "2026-05-07 12:15",
    "Keynote",
    "Software sustainability and community management",
    "Yanini Bellini",
    "rOpenSci",
    "Abstracts.html#software-sustainability-and-community-management",
    
    "2026-05-07 12:15",
    "2026-05-07 12:20",
    "Break",
    "",
    "",
    "",
    "",
    
    "2026-05-07 12:20",
    "2026-05-07 12:22",
    "Session Intro",
    "",
    "",
    "",
    "",
    
    "2026-05-07 12:22",
    "2026-05-07 12:42",
    "Regular Talk",
    "Bridging the Gap Between Spreadsheets and Shiny: Interactive Clinical Data Entry with esq.handsontable",
    "Anastasiia Kostiv",
    "ESQlabs",
    # "abstracts.html#retrospective-clinical-date-harmonisation-reporting",
    "Abstracts.html#bridging-the-gap-between-spreadsheets-and-shiny-interactive-",
    
    "2026-05-07 12:42",
    "2026-05-07 13:02",
    "Regular Talk",
    "MetaInsight v7: A Comprehensive and Reproducible Shiny App for Network Meta-analysis",
    "Simon Smart",
    "University of Leicester",
    "Abstracts.html#metainsight-v7-a-comprehensive-and-reproducible-shiny-app-fo",
    
    "2026-05-07 13:02",
    "2026-05-07 13:07",
    "Questions",
    "",
    "",
    "",
    "",
    
    "2026-05-07 13:07",
    "2026-05-07 13:12",
    "Break",
    "",
    "",
    "",
    "",
    
    "2026-05-07 13:12",
    "2026-05-07 13:14",
    "Session Intro",
    "",
    "",
    "",
    "",
    
    "2026-05-07 13:14",
    "2026-05-07 13:34",
    "Regular Talk",
    "NIH: Not Invented Here: balancing unique software needs vs out-of-box (almost) perfect generic solution. Teal 'module-first' as a case study.",
    "Dror Berel",
    "Consultant",
    "Abstracts.html#nih-not-invented-here-balancing-unique-software-needs-vs-out",
    
    "2026-05-07 13:34",
    "2026-05-07 13:44",
    "Lightning Talk",
    "CougarStats: An Interactive R-Based Platform for Applied Health Data Science",
    "Ashok Krishnamurthy & Darren Law Yan Lun",
    "Mount Royal University",
    "Abstracts.html#cougarstats-an-interactive-r-based-platform-for-applied-heal",
    
    "2026-05-07 13:44",
    "2026-05-07 13:54",
    "Lightning Talk",
    "Toggling Between Traditional and Chat-Based Data Filters in Shiny",
    "Alex Zajichek",
    "Cleveland Clinic",
    "Abstracts.html#toggling-between-traditional-and-chat-based-data-filters-in-",
    
    "2026-05-07 13:54",
    "2026-05-07 13:59",
    "Questions",
    "",
    "",
    "",
    "",
    
    "2026-05-07 13:59",
    "2026-05-07 14:04",
    "Break",
    "",
    "",
    "",
    "",
    
    "2026-05-07 14:04",
    "2026-05-07 14:06",
    "Session Intro",
    "",
    "",
    "",
    "",
    
    "2026-05-07 14:06",
    "2026-05-07 14:26",
    "Regular Talk",
    "From Prompt to Proof: Governing LLM Intelligence in Pharma with Snowflake and Shiny",
    "Tanya Cashorali",
    "TCB Analytics",
    "Abstracts.html#from-prompt-to-proof-governing-llm-intelligence-in-pharma-wi",
    
    "2026-05-07 14:26",
    "2026-05-07 14:36",
    "Lightning Talk",
    "Report Agent: An LLM-Powered Framework for Automated Shell-to-Code Report Generation",
    "Lucie Zhang",
    "Genentech",
    "Abstracts.html#report-agent-an-llm-powered-framework-for-automated-shell-to",
    
    "2026-05-07 14:36",
    "2026-05-07 14:46",
    "Lightning Talk",
    "AI-Assisted Authoring of an Open-Access Portuguese Biostatistics Book in Quarto and R",
    "Audrei Pavanello & Leonardo Pestillo de Oliveira",
    "Cesumar Institute of Science, Technology and Innovation",
    "Abstracts.html#ai-assisted-authoring-of-an-open-access-portuguese-biostatis",
    
    "2026-05-07 14:46",
    "2026-05-07 14:51",
    "Questions",
    "",
    "",
    "",
    "",
    
    "2026-05-07 14:51",
    "2026-05-07 14:56",
    "Break",
    "",
    "",
    "",
    "",
    
    "2026-05-07 14:56",
    "2026-05-07 14:58",
    "Session Intro",
    "",
    "",
    "",
    "",
    
    "2026-05-07 14:58",
    "2026-05-07 15:18",
    "Regular Talk",
    "Supercharging Reproducible Research in R with GitHub Actions",
    "Jonathan Pearce",
    "McGill University",
    "Abstracts.html#supercharging-reproducible-research-in-r-with-github-actions",
    
    "2026-05-07 15:18",
    "2026-05-07 15:38",
    "Regular Talk",
    "Care and Feeding of Your Biostats Team: Scaling best practices in a large hybrid SAS/R team",
    "John Ehrlinger",
    "Cleveland Clinic",
    "Abstracts.html#care-and-feeding-of-your-biostats-team-scaling-best-practice",
    
    "2026-05-07 15:38",
    "2026-05-07 15:43",
    "Questions",
    "",
    "",
    "",
    "",
    
    "2026-05-07 15:43",
    "2026-05-07 15:48",
    "Break",
    "",
    "",
    "",
    "",
    
    "2026-05-07 15:48",
    "2026-05-07 15:50",
    "Session Intro",
    "",
    "",
    "",
    "",
    
    "2026-05-07 15:50",
    "2026-05-07 16:50",
    "Keynote",
    "Voices in the Code: A Story about People, Their Values, and the Algorithm They Made",
    "David Robinson",
    "OpenAI",
    "Abstracts.html#voices-in-the-code-a-story-about-people-their-values-and-the",
    
    "2026-05-07 16:50",
    "2026-05-07 16:55",
    "Break",
    "",
    "",
    "",
    "",
    
    "2026-05-07 16:55",
    "2026-05-07 16:57",
    "Session Intro",
    "",
    "",
    "",
    "",
    
    "2026-05-07 16:57",
    "2026-05-07 17:07",
    "Lightning Talk",
    "Streamlined Access to NHANES Data: Fast, Harmonized, and Reliable",
    "Natalie Neugaard & Amrit Baral",
    "University of Miami",
    "Abstracts.html#streamlined-access-to-nhanes-data-fast-harmonized-and-reliab",
    
    "2026-05-07 17:07",
    "2026-05-07 17:17",
    "Lightning Talk",
    "Infodengue intramunicipal - An R package under development",
    "Ayrton Gouveia & Thais Riback",
    "Fundação Oswaldo Cruz",
    "Abstracts.html#infodengue-intramunicipal-an-r-package-under-development",
    
    "2026-05-07 17:17",
    "2026-05-07 17:27",
    "Lightning Talk",
    "REDCapDM: Managing REDCap Data",
    "João Carmezim",
    "IGTP",
    "Abstracts.html#redcapdm-managing-redcap-data",
    
    "2026-05-07 17:27",
    "2026-05-07 17:32",
    "Questions",
    "",
    "",
    "",
    "",

    "2026-05-07 17:32",
    "2026-05-07 17:37",
    "Closing remarks",
    "",
    "Beth Atkinson",
    "Mayo Clinic",
    ""
  ) |>
  dplyr::mutate(
    t_speakers = dplyr::if_else(t_companies != "", paste0(t_speakers, ","), t_speakers),
    duration = time_length(ymd_hm(end_time) - ymd_hm(start_time), unit = "mins")
  )
```

```{r}
# Create a table for the day of events
gt(schedule_day_4) |>
  tab_header(title = md("<br>Meeting Day 1<br>Thursday, May 7, 2026<br><br>")) |> # <- insert the date
  fmt_time(columns = c(start_time, end_time), time_style = "h_m_p") |>
  fmt_duration(
    columns = duration,
    input_units = "minutes",
    output_units = c("hours", "minutes")
  ) |>
  cols_move(columns = duration, after = end_time) |>
  cols_merge(
    columns = c(t_type, t_title, t_speakers, t_companies, url_link),
    pattern = html(html_pattern)
  ) |>
  cols_label(
    start_time ~ "Start Time",
    end_time ~ "End Time",
    duration ~ "Duration",
    t_type ~ ""
  ) |>
  cols_align(align = "center") |>
  cols_width(
    c(start_time, end_time, duration) ~ px(90),
    everything() ~ px(600)
  ) |>
  opt_align_table_header(align = "left") |>
  tab_options(
    heading.background.color = "lightblue",
    column_labels.background.color = "gray85",
    table.width = pct(100)
  ) |>
    tab_style(
        locations = cells_body(rows = t_type == "Break"),
        style = cell_fill(color = "darkseagreen2", alpha = 0.5)
    ) |>
    tab_style(
        locations = cells_body(rows = t_type == "Questions"),
        style = cell_fill(color = "darkseagreen3", alpha = 0.5)
    ) |>
    tab_style(
        locations = cells_body(rows = t_type == "Session Intro"),
        style = cell_fill(color = "darkseagreen3", alpha = 0.5)
    )
```

# Meeting Day 2 

```{r, day5}
# Day 5
schedule_day_5 <-
  dplyr::tribble(
    ~start_time,
    ~end_time,
    ~t_type,
    ~t_title,
    ~t_speakers,
    ~t_companies,
    ~url_link,

    "2026-05-08 11:00",
    "2026-05-08 11:15",
    "Opening Remarks",
    "",
    "Emily Zabor",
    "Cleveland Clinic",
    "",

    "2026-05-08 11:15",
    "2026-05-08 12:15",
    "Keynote",
    "The Truth Seekers: Learning How to Assess Generative AI from Professional Sceptics",
    "Peter Gruber",
    "USI Università della Svizzera italiana",
    "Abstracts.html#the-truth-seekers-learning-how-to-assess-generative-ai-from-",
    
    "2026-05-08 12:15",
    "2026-05-08 12:20",
    "Break",
    "",
    "",
    "",
    "",
    
    "2026-05-08 12:20",
    "2026-05-08 12:22",
    "Session Intro",
    "",
    "",
    "",
    "",

    "2026-05-08 12:22",
    "2026-05-08 12:42",
    "Regular Talk",
    "bulkreadr: Fast, Reproducible Bulk Data Import for R-Based Research Workflows",
    "Ezekiel Ogundepo",
    "African Institute for Mathematical Sciences",
    "Abstracts.html#bulkreadr-fast-reproducible-bulk-data-import-for-r-based-res",
    
    "2026-05-08 12:42",
    "2026-05-08 12:52",
    "Lightning Talk",
    "From Chaos to Consistency: Building a Long‑Lasting Polish Arthroplasty Registry Data Pipeline",
    "Dominik Żabiński",
    "Gruca Orthopaedic and Trauma Teaching Hospital",
    "Abstracts.html#from-chaos-to-consistency-building-a-long-lasting-polish-art",
    
    "2026-05-08 12:52",
    "2026-05-08 13:02",
    "Lightning Talk",
    "Encapsulated Test Coverage: test.assessr – a package for R unit testing",
    "Edward Gillian",
    "Sanofi",
    "Abstracts.html#encapsulated-test-coverage-testassessr-a-package-for-r-unit-",
    
    "2026-05-08 13:02",
    "2026-05-08 13:07",
    "Questions",
    "",
    "",
    "",
    "",
    
    "2026-05-08 13:07",
    "2026-05-08 13:12",
    "Break",
    "",
    "",
    "",
    "",
    
    "2026-05-08 13:12",
    "2026-05-08 13:14",
    "Session Intro",
    "",
    "",
    "",
    "",
    
    "2026-05-08 13:14",
    "2026-05-08 13:34",
    "Regular Talk",
    "blockr: Clinical Data Analysis without Code",
    "Christoph Sax",
    "cynkra / University of Basel",
    "Abstracts.html#blockr-clinical-data-analysis-without-code",
    
    "2026-05-08 13:34",
    "2026-05-08 13:44",
    "Lightning Talk",
    "sumExtras: Streamlining Table Workflows in Clinical Research with R
",
    "Kyle Grealis",
    "University of Miami",
    "Abstracts.html#sumextras-streamlining-table-workflows-in-clinical-research-",

    "2026-05-08 13:44",
    "2026-05-08 13:54",
    "Lightning Talk",
    "An R-Based Pipeline for Resource-Optimized Participant Selection in High-Cost Clinical Research
",
    "Aparna Bhattacharyya",
    "Johns Hopkins University",
    "Abstracts.html#an-r-based-pipeline-for-resource-optimized-participant-selec",

    "2026-05-08 13:54",
    "2026-05-08 13:59",
    "Questions",
    "",
    "",
    "",
    "",

    "2026-05-08 13:59",
    "2026-05-08 14:04",
    "Break",
    "",
    "",
    "",
    "",
    
    "2026-05-08 14:04",
    "2026-05-08 14:06",
    "Session Intro",
    "",
    "",
    "",
    "",

    "2026-05-08 14:06",
    "2026-05-08 14:26",
    "Regular Talk",
    "medicalcoder: A Unified and Longitudinally Aware Framework for ICD-Based Comorbidity Assessment in R",
    "Peter DeWitt",
    "University of Colorado Anschutz",
    "Abstracts.html#medicalcoder-a-unified-and-longitudinally-aware-framework-fo",

    "2026-05-08 14:26",
    "2026-05-08 14:36",
    "Lightning Talk",
    "Modeling Fall Risk with Staged Trees and Expert Judgement",
    "Rachel Wilkerson & Anika Dachiraju",
    "Baylor University",
    "Abstracts.html#modeling-fall-risk-with-staged-trees-and-expert-judgement",

    "2026-05-08 14:36",
    "2026-05-08 14:46",
    "Lightning Talk",
    "Using ggregions for building intuitive coding interfaces for anatomical visualizations",
    "Evangeline (Gina) Reynolds",
    "Consultant",
    "Abstracts.html#using-ggregions-for-building-intuitive-coding-interfaces-for",

    "2026-05-08 14:46",
    "2026-05-08 14:51",
    "Questions",
    "",
    "",
    "",
    "",

    "2026-05-08 14:51",
    "2026-05-08 14:56",
    "Break",
    "",
    "",
    "",
    "",
    
    "2026-05-08 14:56",
    "2026-05-08 14:58",
    "Session Intro",
    "",
    "",
    "",
    "",

    "2026-05-08 14:58",
    "2026-05-08 15:18",
    "Regular Talk",
    "Beyond Sequential: Scaling Existing Medical Pipelines with 'futurize'",
    "Henrik Bengtsson",
    "University of California San Francisco",
    "Abstracts.html#beyond-sequential-scaling-existing-medical-pipelines-with-fu",

    "2026-05-08 15:18",
    "2026-05-08 15:28",
    "Lightning Talk",
    "Parallel computing in R to analyze big health data",
    "Ariel Mundo Ortiz",
    "Centre de recherche du CHUM",
    "Abstracts.html#parallel-computing-in-r-to-analyze-big-health-data",

    "2026-05-08 15:28",
    "2026-05-08 15:38",
    "Lightning Talk",
    "The MBCproject R Package: Enabling reproducible analysis of multi-omic data in metastatic breast cancer",
    "Diana Garcia Cortes",
    "Dana Farber Cancer Institute",
    "Abstracts.html#the-mbcproject-r-package-enabling-reproducible-analysis-of-m",

    "2026-05-08 15:38",
    "2026-05-08 15:43",
    "Questions",
    "",
    "",
    "",
    "",

    "2026-05-08 15:43",
    "2026-05-08 15:48",
    "Break",
    "",
    "",
    "",
    "",
    
    "2026-05-08 15:48",
    "2026-05-08 15:50",
    "Session Intro",
    "",
    "",
    "",
    "",

    "2026-05-08 15:50",
    "2026-05-08 16:10",
    "Regular Talk",
    "Synthetic by Design: Pairing toysurveydata and NSSP Synthetic Data Generator for Privacy-Safe Public Health Training and Development",
    "Abigail Stamm & Eric Kvale",
    "Minnesota Department of Health",
    "Abstracts.html#synthetic-by-design-pairing-toysurveydata-and-nssp-synthetic",

    "2026-05-08 16:10",
    "2026-05-08 16:20",
    "Lightning Talk",
    "DIVINE: Curated Datasets and Tools for Medical Data",
    "Natàlia Pallarès & João Carmezim",
    "IDIBAPS/IGTP",
    "Abstracts.html#divine-curated-datasets-and-tools-for-medical-data",

    "2026-05-08 16:20",
    "2026-05-08 16:30",
    "Lightning Talk",
    "Preventing Data Leakage in Clinical Machine Learning: Guarded Resampling Workflows with fastml in R",
    "Fikret Bartu Yurdacan",
    "Trakya University",
    "Abstracts.html#preventing-data-leakage-in-clinical-machine-learning-guarded",

    "2026-05-08 16:30",
    "2026-05-08 16:35",
    "Questions",
    "",
    "",
    "",
    "",

    "2026-05-08 16:35",
    "2026-05-08 16:40",
    "Break",
    "",
    "",
    "",
    "",
    
    "2026-05-08 16:40",
    "2026-05-08 16:42",
    "Session Intro",
    "",
    "",
    "",
    "",

    "2026-05-08 16:42",
    "2026-05-08 17:02",
    "Regular Talk",
    "When Quant Meets Qual: Extending the R Ecosystem for Qualitative Data",
    "Abiraahmi Shankar",
    "New York University",
    "Abstracts.html#when-quant-meets-qual-extending-the-r-ecosystem-for-qualitat",

    "2026-05-08 17:02",
    "2026-05-08 17:22",
    "Regular Talk",
    "Rapid and comprehensive power analysis in R, with a focus on planned error control for multiple outcomes",
    "Kristen Hunter & Luke Miratrix",
    "University of New South Wales",
    "Abstracts.html#rapid-and-comprehensive-power-analysis-in-r-with-a-focus-on-",

    "2026-05-08 17:22",
    "2026-05-08 17:27",
    "Questions",
    "",
    "",
    "",
    "",

    "2026-05-08 17:27",
    "2026-05-08 17:32",
    "Closing Remarks",
    "",
    "Ray Balise",
    "University of Miami",
    ""
  ) |>
  dplyr::mutate(
    t_speakers = dplyr::if_else(t_companies != "", paste0(t_speakers, ","), t_speakers),
    duration = time_length(ymd_hm(end_time) - ymd_hm(start_time), unit = "mins")
  )
```

```{r}
# Create a table for the day of events
gt(schedule_day_5) |>
  tab_header(title = md("<br>Meeting Day 2<br>Friday, May 8, 2026<br><br>")) |> # <- insert the date
  fmt_time(columns = c(start_time, end_time), time_style = "h_m_p") |>
  fmt_duration(
    columns = duration,
    input_units = "minutes",
    output_units = c("hours", "minutes")
  ) |>
  cols_move(columns = duration, after = end_time) |>
  cols_merge(
    columns = c(t_type, t_title, t_speakers, t_companies, url_link),
    pattern = html(html_pattern)
  ) |>
  cols_label(
    start_time ~ "Start Time",
    end_time ~ "End Time",
    duration ~ "Duration",
    t_type ~ ""
  ) |>
  cols_align(align = "center") |>
  cols_width(
    c(start_time, end_time, duration) ~ px(90),
    everything() ~ px(600)
  ) |>
  opt_align_table_header(align = "left") |>
  tab_options(
    heading.background.color = "lightblue",
    column_labels.background.color = "gray85",
    table.width = pct(100)
  ) |>
    tab_style(
        locations = cells_body(rows = t_type == "Break"),
        style = cell_fill(color = "darkseagreen2", alpha = 0.5)
    ) |>
    tab_style(
        locations = cells_body(rows = t_type == "Questions"),
        style = cell_fill(color = "darkseagreen3", alpha = 0.5)
    ) |>
    tab_style(
        locations = cells_body(rows = t_type == "Session Intro"),
        style = cell_fill(color = "darkseagreen3", alpha = 0.5)
    )
```
