---
title: "Speaker guide"
---

## Welcome!

This page is intended for folks who have had their abstract accepted for a lightning talk or regular talk at R/Medicine 2025. Congratulations! We are excited to welcome you as a presenter. As a reminder, the event will take place virtually on Thursday and Friday, June 13-14, on Eastern Daylight Time. Please click through the tabs on this page to access information.

## Deadlines

-   **Pre-Recording Video Submission Due Date** (mandatory for lightning talks, recommended for regular talks with only one speaker): Monday, June 2

-   **Event Dates:** Monday, June 9 -- Friday, June 13

-   **Timezone:** Eastern Daylight Time

## Schedule and Timing

The schedule has been posted on the R/Medicine web site.

-   All lightning talks are ten (10) minutes in total (including Q&A).

-   All regular talks are twenty (20) minutes in total (including Q&A).

*Please ensure your pre-recorded talk does not go over the allotted time*

## Platform & Specifications

We will be using the virtual platform Zoom Events that will allow pre-recorded talks to play while speakers join the chat live (and drop links into the chat) for Q&A during the session.

## Pre-recording Information & Tools

All regular talk and lightning talk speakers must pre-record their talk, which will be played through the event platform.

Some suggested tools to use for recording are Quicktime, Zoom, a screen recorder, or something similar. The recording should show your slides or screen and optionally yourself, using a picture in picture style format. **Please share the actual video file, in MP4 format, not a link to a streaming service such as YouTube or Vimeo. The file should be named as "WeekdayOfTalk-Firstname-Lastname.mp4, for example "Thursday-Jane-Doe.mp4" for a talk by Jane Doe that will take place on Thursday.** Email this recording to us at jesse\@storychangesculture.org by midnight EDT on June 2. If your file is too large to email, you can upload it [here](https://docs.google.com/forms/d/e/1FAIpQLSc6VJB7dBT0M69LpG71qaD1i8k9XwbbKDUShZXd88sNpo9Rvg/viewform?usp=sharing&ouid=105203521223356605996).

Please feel free to [reach out](mailto:r-medicine-conf@r-consortium.org) with any questions.

## Prepare Your Slides

-   Remember that people can either listen to you speak ***or*** read your slides, they can ***not*** do both at once.

-   Keep your slides visually minimal

    -   Your slides should support your message, not distract from what you are saying.

-   Use color to highlight key points and/or key words.

-   Set your base font size to be somewhat large (16 or 18 point).

-   Avoid showing Blue on Black.

-   Use high contrast colors between your slide background and text [contrastchecker](https://webaim.org/resources/contrastchecker/)

-   Make sure all your slides are color blind safe. Take a screenshot and paste the image here: [color-blindness-simulator](https://www.color-blindness.com/coblis-color-blindness-simulator/). Be sure to check all the different forms of color vision weakness including Monochromacy/Achromatopsia.

### Configure your CodeEditor/IDE

-   Set the font on your code editor to be large enough that you can read the text from a few feet away.

-   If you use the RStudio or Positron IDE you can make everything larger with `cmd +` on Mac or `ctrl +` on Windows.

-   If you work on a large display, take a screen shot showing your code and view it on a 13 inch laptop or tablet.

### Showing Code In Your IDE

-   Remember that most IDEs can collapse code blocks.

    -   Consider hiding material that you have not talked about yet.

    -   If a code block does setup, show it and collapse it.

### Showing Code In Slides

-   Consider highlighting key points as you are taking about them.

-   If you are working in Quarto you can fold/show your code using code chunk options like this:

```{{r}}
#| code-fold: true
#| code-summary: "Show the code"

# code to show goes here
```

-   Showing code with line numbers makes it easier for people to ask questions.

-   If you are making slide with Quarto you can draw attention to lines of code with a couple of techniques. Consider these options:

    -   [Code Annotation](https://quarto.org/docs/blog/posts/2023-03-13-code-annotation/)

    -   [Code line highlighting](https://www.pipinghotdata.com/posts/2022-05-12-code-line-highlighting-in-quarto-revealjs-presentations/)

### Slide templates

R/Medicine slide templates are available for:

-   **Powerpoint**. Download the template [here](https://docs.google.com/presentation/d/1147BW-lYMz1Re5vspoOONiuh2iK-GOx-/edit?usp=drive_link&ouid=109461157699922412522&rtpof=true&sd=true).
-   **Quarto**. See details below.

#### Creating RMed Slides in Quarto

To prepare your RevealJS presentation for R/Medicine 2025 using our prebuilt template, follow this outline.

1.  Install the {rUM} package from their `dev` branch:

``` r
remotes::install_github("RaymondBalise/rUM@dev")
```

2.  Initialize a new slide project that includes the RMed templates. Be sure to include `template = "rmed2025"`. A `slides` directory will be created in your current path as defined by `here::here()` unless you use the `path =` argument. This demonstration will create the directory evaluated by `here::here()`:

For example, this code will make a slides folder in your working directory:

``` r
# rUM::write_slides("<your presentation name>", template = "rmed2025")
rUM::write_slides("rmed2025_demo", template = "rmed2025")
```

If you are on Mac and want to have a slides folder added to your desktop you can do this:

``` r
rUM::write_slides("rmed2025_demo", path = "~/Desktop/", template = "rmed2025")
```

3.  The `slides` directory will include:

-   `<project>.qmd` (The demonstration created `rmed2025_demo.qmd`)
-   `slides.scss` for presentation styling
-   `rstudio_default-light.theme` that will render your code examples (i.e., syntax highlighting) as displayed in RStudio's light theme
-   `img` directory containing template background, hex logo, and `.ico` file to add styling to your browser's tab once the presentation is rendered.
    -   NOTE: `clean_title_page.html` includes JavaScript that modifies elements on the title page only. We recommend against modifying this file.

4.  Render the document using either the RStudio "Knit" or Positron "Preview" GUI buttons, Ctrl+Shift+K (CMD+Shift+K for macOS), or use the terminal command:

``` bash
quarto preview slides/<project>.qmd --no-browser
```

We recommend you modify the following values in the presentation YAML:

-   Title, subtitle, & author details
-   `footer`: complete the URL to the project repository for a working HTML hyperlink
    -   Alter the text (`[Slides are here]`) for a more custom hyperlink at the slide bottom

## Technical Tips for Virtual Presentations

-   **Audio** -- as counterintuitive as it may sound, the single most important factor in a good video, is the audio quality.

-   **Eliminate ambient noise** -- close the doors and windows. You'd be surprised how much environmental noise gets picked up.

-   **Lighting** -- Do not put lights overhead and don't put any lights or windows behind you as they will alter the light levels in your videos and create shadows.

-   **Background** -- don't be afraid to show your natural environment -- bookcases, plants, paintings -- as long as they are not too distracting.

-   **Framing** -- place yourself slightly off-center to the left or right rather than directly in the middle of the frame.

-   **Camera Height** -- the lens should either be directly level or pointing ever so slightly downwards towards your face.

-   **Stand** -- we recommend you stand during your presentation to help project your voice and improve your posture. However, if you're more comfortable sitting, then please do.

-   **Timer** -- Have a clock to keep track of the time you have remaining.

From: <https://www.greatspeech.co/video-presentations/>

## Lighting, Webcam and Microphone Best Practices

### Best Practices for Lighting

-   For best results, use natural light and supplement with additional light as needed.

-   Keep natural light in front of you to avoid shadows. A bright window behind you can make you appear as a dark silhouette.

-   Interior rooms with no natural light source may require additional targeted lighting, such as a ring light, to brighten the speaker's face.

### Best Practices for Webcams

-   To ensure the speaker is looking directly at the audience, place the webcam at eye level.

-   Avoid distracting backgrounds by checking the surroundings behind you to make sure there are no distracting colors or movement.

-   Presenters should use chairs that are adjustable for height but do not swivel. Swiveling on camera creates a poor attendee experience and can be distracting.

### Best Practices for Microphones

-   Use external microphones whenever available, as microphones built into computers and cameras often have lower quality.

-   An external microphone allows the speaker to place it in the optimal location for sound.

-   Place the microphone close to the speaker's mouth, but not in the camera view.

-   Test audio levels in advance.

-   Manage noise by turning off fans, phones, or speakers and keep ambient noise to a minimum.

-   Do not touch the microphone while unmuted

-   Send your video to a friend prior to submission to check the sound and video quality

### Dress Code

There is no dress code for presentations, and we encourage you to be comfortable. That said, you must be aware that the [Code of Conduct](https://r-medicine-2021.netlify.app/code-of-conduct/) applies to this space, both in terms of what you show on camera and what you say. We ask that you be tasteful and considerate in choosing your clothing and surroundings. Keep in mind that we are a global community. Please refrain from wearing shirts with global brand logos that are not your own. Solid colors (not white) also work best instead of prints.

## Live Q&A

For the main meeting on Thursday and Friday, it is required to have a presenter or co-presenter available for the live chat while the pre-recorded talk plays. This is one of the best features of R/Medicine, as the whole community gets to discuss the topic with the speaker during the talk without being rude. It is often helpful to prepare for the live chat by assembling a document with any links, references, etc. that you can copy and paste into the chat when appropriate. This includes links to slides or GitHub repos, as appropriate.

-   **Learn the Content**: Familiarity with the content allows a speaker to focus on presenting, rather than trying to remember the points to make. To minimize worry about forgetting elements of the presentation, include notes in your presentation file and have a prepared e-document of your links, script, or talking points that you can paste into the chat.

-   **Practice Makes Perfect**: Speakers should practice their content delivery in the environment in which they will deliver it, such as in front of a computer. Presenting alone to a computer can be awkward at first. To make speakers more comfortable, ask colleagues, roommates, or family to sit in front so they can present to familiar faces.

-   **Understand the Tools**: Speakers should understand and utilize the content options available to them, to maximize the effectiveness of the presentation technology. It's important to know the basic functions of the software, e.g. how to advance slides, manage Zoom Q&A or chats, before the presentation.

-   **Speak Up**: Check audio levels before presenting, but also make sure to breathe at regular intervals to speak audibly and clearly. Maintaining a clear, even tone throughout the presentation will allow the audience to hear it without adjusting their volume settings.

-   **Look at Your Camera**: If presenting via video, remember, the webcam is your link to your audience. Make eye contact with the camera so it appears to the audience that you are speaking directly to them.

-   **Don't Fear Mistakes**: Humans make mistakes, even during presentations. Realize that flubs happen and they won't derail your presentation -- unless you let them. Just keep going in your planned presentation and remember, the audience is forgiving.

-   **Be Prepared**: During the presentation, have a glass of water nearby to sip as needed. Also, keep handy a printout of your slides or notes in case you need to refer to them.

From: <https://www.inxpo.com/assets/pdfs/litepapers/How-To-Be-An-Engaging-Speaker.pdf>

## Inclusive Speaker Orientation Online Course

The Linux Foundation, in collaboration with the National Center for Women in Technology (NCWIT), has created an [online course](https://training.linuxfoundation.org/content/inclusive-speaker-orientation) designed to teach the viewer about inclusion, diversity, and unconscious bias. We highly recommend all of our speakers, [watch the course](https://training.linuxfoundation.org/content/inclusive-speaker-orientation) to learn tips/tools to use when speaking to encourage inclusivity in presentations and messaging.

## Code of Conduct

Please read and abide by our code of conduct, which can be found [here](https://r-medicine-2021.netlify.app/code-of-conduct/). We ask that speakers especially review this code of conduct and are inclusive in the **words and images** used during their presentation.

## Links to additional resources

[**Best Gear for Online Meetings**](https://www.cnet.com/how-to/best-gear-for-online-meetings-webcams-lights-mics-tripods-and-more/) -- Webcams, lights, mics, tripods and more

[**19 Video Presentation Tips**](https://www.greatspeech.co/video-presentations/#.XtFN_y_Mx-U) to help you give a great presentation (even if you hate the way you look on camera)

[**9 Tips for Giving Engaging Virtual Presentations**](https://pantheon.io/blog/tips-for-virtual-presentations) -- This article gives 9 tips and within each tip has folks from the tech world giving their advice in a fun/relatable way.

[**PACE Acronym for Virtual Presentations**](https://magneticspeaking.com/9-important-tips-for-virtual-presentations/)

[**Checklist for Speakers**](https://www.blueskyelearn.com/for-presenters-a-virtual-event-checklist/) -- this article provides checklists applicable for speakers that are live streaming.

[**R-Ladies video tips**](https://rladies.org/blog/2025-02-03-submit_posit_conf/)

[**Your Perfect Tech Talk**](https://www.youtube.com/watch?v=AzVr_nsKoZs)

[**A general MIT lecture on How to Speak**](https://www.youtube.com/watch?v=Unzc731iCUY)
